In [1]:
import numpy as np
import sys

In [2]:
np.array([3,5,6,44,3])


array([ 3,  5,  6, 44,  3])

In [3]:
a=np.array([3,5,6,44,3])

In [4]:
print(a)

[ 3  5  6 44  3]


In [5]:
print(a[::-1])

[ 3 44  6  5  3]


In [6]:
a[3]

44

In [7]:
a[2]

6

In [11]:
a[0::3]

array([ 3, 44])

### Dimensions and shapes

In [12]:
# Pandas
# Getting the data
# Processing the data
# Visualizing the data
# Analyzing the data
# Graphs and pie charts
# Machine Learning..